### ISSUE TITLE
look into failing builds for new projects

### ISSUE THREAD

**Issue by afeld** [18F/concourse-compliance-testing#93]
Seems to be consistent across all new projects after following the [new project steps](https://github.com/18F/concourse-compliance-testing#adding-a-project). In `filter-project-data`:

```
/tmp/build/af6792a7/scripts/lib/team_data_filterer.rb:32:in `initialize': No such file or directory @ rb_sysopen - /tmp/build/af6792a7/project-data/project.json (Errno::ENOENT)
    from /tmp/build/af6792a7/scripts/lib/team_data_filterer.rb:32:in `new'
    from /tmp/build/af6792a7/scripts/lib/team_data_filterer.rb:32:in `read_json'
    from ./scripts/tasks/filter-project-data/task.rb:6:in `<main>'
```

e.g. https://ci.cloud.gov/pipelines/zap/jobs/zap-ondemand-cg-landing/builds/2

/cc @dlapiduz

**Comment by afeld** [comment]
Dupe of #95.
